-- ============================================================
--  Smart Diet Planner -- Oracle 11g XE Compatible Schema
--  Replaces IDENTITY columns with SEQUENCE + TRIGGER pattern
--  Compatible with: SQL*Plus, Oracle 11g XE
--  Run order: sequences -> tables -> triggers -> inserts
-- ============================================================

-- ============================================================
--  STEP 0: Clean up existing objects (safe re-run)
--  DROP order respects foreign key dependencies:
--  child tables first, then parent tables, then sequences
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_meals_bi';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_streaks_bi';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_progress_bi'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_diet_plan_bi';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_users_bi';    EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE meals     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE streaks   CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE progress  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE diet_plan CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_meals';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_streaks';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_progress';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_diet_plan'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_users';     EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
--  STEP 1: SEQUENCES (replace GENERATED BY DEFAULT AS IDENTITY)
--  START WITH 1, INCREMENT BY 1, no upper limit, cached for speed
-- ============================================================

CREATE SEQUENCE seq_users
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

CREATE SEQUENCE seq_diet_plan
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

CREATE SEQUENCE seq_progress
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

CREATE SEQUENCE seq_streaks
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

CREATE SEQUENCE seq_meals
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

-- ============================================================
--  STEP 2: TABLES
--  Notes:
--   - NUMBER(p,s) used instead of FLOAT for Oracle 11g safety
--   - SYSDATE used for default dates (CURRENT_DATE is fine too)
--   - VARCHAR2 lengths kept identical to original schema
-- ============================================================

-- ── USERS ────────────────────────────────────────────────────
CREATE TABLE users (
    user_id     NUMBER          NOT NULL,
    name        VARCHAR2(100)   NOT NULL,
    email       VARCHAR2(150)   NOT NULL,
    password    VARCHAR2(255)   NOT NULL,
    age         NUMBER(3)       NOT NULL,
    height_cm   NUMBER(5,2)     NOT NULL,
    weight_kg   NUMBER(5,2)     NOT NULL,
    gender      CHAR(1),
    goal        VARCHAR2(20),
    bmr         NUMBER(7,2),
    target_cal  NUMBER(7,2),
    created_at  DATE            DEFAULT SYSDATE,
    -- Primary Key
    CONSTRAINT pk_users         PRIMARY KEY (user_id),
    -- Unique email
    CONSTRAINT uq_users_email   UNIQUE (email),
    -- Gender must be M or F
    CONSTRAINT ck_users_gender  CHECK (gender IN ('M', 'F')),
    -- Goal must be one of three values
    CONSTRAINT ck_users_goal    CHECK (goal IN ('loss', 'gain', 'maintain'))
);

-- ── DIET_PLAN ─────────────────────────────────────────────────
CREATE TABLE diet_plan (
    plan_id     NUMBER          NOT NULL,
    user_id     NUMBER,
    plan_date   DATE            DEFAULT SYSDATE,
    breakfast   VARCHAR2(500),
    lunch       VARCHAR2(500),
    dinner      VARCHAR2(500),
    total_cal   NUMBER(7,2),
    water_ml    NUMBER(5),
    -- Primary Key
    CONSTRAINT pk_diet_plan     PRIMARY KEY (plan_id),
    -- Foreign Key to users with cascade delete
    CONSTRAINT fk_diet_user     FOREIGN KEY (user_id)
                                REFERENCES users(user_id)
                                ON DELETE CASCADE
);

-- ── PROGRESS ──────────────────────────────────────────────────
CREATE TABLE progress (
    progress_id     NUMBER      NOT NULL,
    user_id         NUMBER,
    log_date        DATE        DEFAULT SYSDATE,
    weight_kg       NUMBER(5,2),
    calories_eaten  NUMBER(7,2),
    notes           VARCHAR2(300),
    -- Primary Key
    CONSTRAINT pk_progress      PRIMARY KEY (progress_id),
    -- Foreign Key to users with cascade delete
    CONSTRAINT fk_progress_user FOREIGN KEY (user_id)
                                REFERENCES users(user_id)
                                ON DELETE CASCADE
);

-- ── STREAKS ───────────────────────────────────────────────────
CREATE TABLE streaks (
    streak_id       NUMBER      NOT NULL,
    user_id         NUMBER,
    current_streak  NUMBER      DEFAULT 0,
    longest_streak  NUMBER      DEFAULT 0,
    last_log_date   DATE,
    badge_7         CHAR(1)     DEFAULT 'N',
    badge_14        CHAR(1)     DEFAULT 'N',
    badge_30        CHAR(1)     DEFAULT 'N',
    -- Primary Key
    CONSTRAINT pk_streaks       PRIMARY KEY (streak_id),
    -- Foreign Key to users with cascade delete
    CONSTRAINT fk_streaks_user  FOREIGN KEY (user_id)
                                REFERENCES users(user_id)
                                ON DELETE CASCADE,
    -- Badge values restricted to Y/N
    CONSTRAINT ck_badge_7       CHECK (badge_7  IN ('Y','N')),
    CONSTRAINT ck_badge_14      CHECK (badge_14 IN ('Y','N')),
    CONSTRAINT ck_badge_30      CHECK (badge_30 IN ('Y','N'))
);

-- ── MEALS (reference / lookup table) ─────────────────────────
CREATE TABLE meals (
    meal_id     NUMBER          NOT NULL,
    meal_type   VARCHAR2(20),
    name        VARCHAR2(200),
    calories    NUMBER(5),
    protein_g   NUMBER(5,2),
    carbs_g     NUMBER(5,2),
    fat_g       NUMBER(5,2),
    goal_type   VARCHAR2(20),
    -- Primary Key
    CONSTRAINT pk_meals         PRIMARY KEY (meal_id),
    -- Meal type restricted values
    CONSTRAINT ck_meals_type    CHECK (meal_type IN ('breakfast','lunch','dinner','snack'))
);

-- ============================================================
--  STEP 3: BEFORE INSERT TRIGGERS
--  Each trigger pulls the next sequence value into :NEW.pk_col
--  so that INSERT statements do not need to specify the PK.
--  Oracle 11g uses the "FOR EACH ROW" trigger pattern.
-- ============================================================

-- ── Trigger: users ───────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_users_bi
    BEFORE INSERT ON users
    FOR EACH ROW
BEGIN
    -- Only assign a new ID if one was not supplied by the caller
    IF :NEW.user_id IS NULL THEN
        SELECT seq_users.NEXTVAL INTO :NEW.user_id FROM DUAL;
    END IF;
END;
/

-- ── Trigger: diet_plan ───────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_diet_plan_bi
    BEFORE INSERT ON diet_plan
    FOR EACH ROW
BEGIN
    IF :NEW.plan_id IS NULL THEN
        SELECT seq_diet_plan.NEXTVAL INTO :NEW.plan_id FROM DUAL;
    END IF;
END;
/

-- ── Trigger: progress ────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_progress_bi
    BEFORE INSERT ON progress
    FOR EACH ROW
BEGIN
    IF :NEW.progress_id IS NULL THEN
        SELECT seq_progress.NEXTVAL INTO :NEW.progress_id FROM DUAL;
    END IF;
END;
/

-- ── Trigger: streaks ─────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_streaks_bi
    BEFORE INSERT ON streaks
    FOR EACH ROW
BEGIN
    IF :NEW.streak_id IS NULL THEN
        SELECT seq_streaks.NEXTVAL INTO :NEW.streak_id FROM DUAL;
    END IF;
END;
/

-- ── Trigger: meals ───────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_meals_bi
    BEFORE INSERT ON meals
    FOR EACH ROW
BEGIN
    IF :NEW.meal_id IS NULL THEN
        SELECT seq_meals.NEXTVAL INTO :NEW.meal_id FROM DUAL;
    END IF;
END;
/

-- ============================================================
--  STEP 4: SAMPLE DATA INSERTS
--  PK columns are omitted -- triggers auto-assign sequence IDs.
--  All inserts are wrapped in a single transaction; COMMIT at end.
-- ============================================================

-- ── Breakfast meals ───────────────────────────────────────────
INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('breakfast', 'Oats with banana and almond milk', 350, 10, 58, 7, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('breakfast', 'Scrambled eggs (3) with whole wheat toast', 420, 22, 32, 18, 'maintain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('breakfast', 'Paneer paratha with curd and butter', 620, 24, 65, 28, 'gain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('breakfast', 'Greek yogurt with berries and chia seeds', 280, 18, 30, 6, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('breakfast', 'Protein smoothie with banana, whey, peanut butter', 550, 35, 52, 14, 'gain');

-- ── Lunch meals ───────────────────────────────────────────────
INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('lunch', 'Grilled chicken breast with brown rice and salad', 480, 42, 45, 10, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('lunch', 'Dal tadka with 2 rotis and mixed veg', 520, 20, 72, 12, 'maintain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('lunch', 'Chicken biryani with raita and salad', 750, 38, 85, 22, 'gain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('lunch', 'Tuna salad with olive oil dressing and quinoa', 420, 36, 30, 14, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('lunch', 'Rajma rice with ghee and papad', 680, 22, 95, 18, 'gain');

-- ── Dinner meals ──────────────────────────────────────────────
INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('dinner', 'Baked fish with steamed broccoli and sweet potato', 400, 35, 38, 8, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('dinner', 'Palak paneer with 1 roti and cucumber raita', 460, 22, 42, 18, 'maintain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('dinner', 'Mutton curry with naan and onion salad', 720, 40, 68, 28, 'gain');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('dinner', 'Vegetable stir fry with tofu and cauliflower rice', 320, 22, 28, 10, 'loss');

INSERT INTO meals (meal_type, name, calories, protein_g, carbs_g, fat_g, goal_type)
VALUES ('dinner', 'Grilled paneer tikka with dal makhani and rice', 680, 30, 72, 25, 'gain');

COMMIT;

-- ============================================================
--  STEP 5: VERIFICATION QUERIES
--  Run these after the script to confirm everything was created.
-- ============================================================

-- Check all tables exist
SELECT table_name
FROM   user_tables
WHERE  table_name IN ('USERS','DIET_PLAN','PROGRESS','STREAKS','MEALS')
ORDER  BY table_name;

-- Check all sequences exist
SELECT sequence_name
FROM   user_sequences
WHERE  sequence_name IN ('SEQ_USERS','SEQ_DIET_PLAN','SEQ_PROGRESS','SEQ_STREAKS','SEQ_MEALS')
ORDER  BY sequence_name;

-- Check all triggers exist
SELECT trigger_name, table_name, status
FROM   user_triggers
WHERE  trigger_name IN ('TRG_USERS_BI','TRG_DIET_PLAN_BI','TRG_PROGRESS_BI',
                        'TRG_STREAKS_BI','TRG_MEALS_BI')
ORDER  BY trigger_name;

-- Check sample meals were inserted (expect 15 rows)
SELECT meal_type, COUNT(*) AS total
FROM   meals
GROUP  BY meal_type
ORDER  BY meal_type;

-- ============================================================
--  QUICK REFERENCE: How to INSERT into these tables from Java
-- ============================================================
--
--  Because triggers auto-assign PKs, your Java PreparedStatements
--  should NOT include the PK column in the INSERT column list.
--
--  Example for users table:
--    INSERT INTO users
--      (name, email, password, age, height_cm, weight_kg, gender, goal, bmr, target_cal)
--    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
--
--  To get the generated PK back in JDBC (Oracle 11g):
--    String[] cols = {"USER_ID"};
--    PreparedStatement ps = con.prepareStatement(sql, cols);
--    ps.executeUpdate();
--    ResultSet keys = ps.getGeneratedKeys();
--    if (keys.next()) { int newId = keys.getInt(1); }
--
-- ============================================================